#!/bin/bash

# Install Homebrew (http://brew.sh)
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew doctor

brew install wget
brew install git
brew install kitty

brew install slack
brew install skype
brew install telegram-desktop

mkdir -p ~/Projects
cd ~/Projects
# Checkout and install various configs
if [ ! -d dot-files ]; then
  git clone git@github.com:maximkulkin/dot-files.git
  dot-files/install
fi

# Install custom font
cp ~/Projects/dot-files/fonts/*.ttf ~/Library/Fonts

# Checkout and install vim-configs
if [ ! -d vim-configs ]; then
  git clone git@github.com:maximkulkin/vim-configs.git
  vim-configs/install
fi
