#!/bin/bash

# Install Homebrew (http://brew.sh)
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew doctor

# Install Homebrew Cask (http://caskroom.io)
brew install caskroom/cask/brew-cask

brew install wget
brew install git

brew cask install slack
brew cask install skype
brew cask install telegram-desktop
brew cask install google-chrome

mkdir -p ~/Projects
cd ~/Projects
# Checkout and install various configs
if [ ! -d dot-files ]; then
  git clone git@github.com:maximkulkin/dot-files.git
  dot-files/install
fi

# Install custom font
cp ~/Projects/dot-files/fonts/*.ttf ~/Library/Fonts

# Checkout and install vim-configs
if [ ! -d vim-configs ]; then
  git clone git@github.com:maximkulkin/vim-configs.git
  vim-configs/install
fi

echo "Do not forget to install Terminal.app Pro profile"
