#!/bin/bash

# Install Homebrew (http://brew.sh)
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew doctor

# Install Homebrew Cask (http://caskroom.io)
brew install caskroom/cask/brew-cask

brew install wget
brew install git

brew cask install virtualbox
brew cask install vagrant

brew cask install slack
brew cask install skype
brew cask install google-chrome
# VPN software
brew cask install viscosity

mkdir -p ~/Projects
cd ~/Projects
# Checkout and install various configs
if [ ! -d dot-files ]; then
  git clone git@github.com:maximkulkin/dot-files.git
  dot-files/install
fi

# Install custom font
cp ~/Projects/dot-files/Monaco\ for\ Powerline.otf ~/Library/Fonts

# Checkout and install vim-configs
if [ ! -d vim-configs ]; then
  git clone git@github.com:maximkulkin/vim-configs.git
  vim-configs/install
fi
