#!/bin/bash

absolute-path() {
  (cd "$1" && pwd)
}

relative-path() {
  local targetDir="$(absolute-path "$1")"
  local pivotDir="$(absolute-path "$2")"
  echo "${targetDir#$pivotDir/}"
}

relativeDir="$(relative-path "$(dirname "$0")" "$HOME")"

# Configure bash
test -d ~/.dot-files || \
  ln -s $relativeDir ~/.dot-files

grep "source ~/.dot-files/bashrc" ~/.bashrc &>/dev/null || \
  echo "source ~/.dot-files/bashrc" >> ~/.bashrc
echo -e "\nsource ~/.bashrc" >> ~/.bash_profile

# Configure tmux
test -e ~/.tmux.conf || \
  ln -s $relativeDir/tmux.conf ~/.tmux.conf

# Configure Git
ln -s $relativeDir/gitignore ~/.gitignore

git config --global user.name "Maxim Kulkin"
git config --global user.email "maxim.kulkin@gmail.com"
git config --global push.default simple
git config --global rerere.enabled true
git config --global rebase.autosquash true
git config --global core.excludesFile ~/.gitignore
