#!/bin/bash

absolute-path() {
  (cd "$1" && pwd)
}

relative-path() {
  local targetDir="$(absolute-path "$1")"
  local pivotDir="$(absolute-path "$2")"
  echo "${targetDir#$pivotDir/}"
}

relativeDir="$(relative-path "$(dirname "$0")" "$HOME")"

# Configure bash
test -d ~/.dot-files || \
  ln -s $relativeDir ~/.dot-files

grep "source ~/.dot-files/zshrc" ~/.zshrc &>/dev/null || \
  echo "source ~/.dot-files/zshrc" >> ~/.zshrc

# Configure tmux
test -e ~/.tmux.conf || \
  ln -s $relativeDir/tmux.conf ~/.tmux.conf

mkdir -p ~/.tmux
mkdir -p ~/.tmux/plugins
test -d ~/.tmux/plugins/tpm || \
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Configure Git
ln -s $relativeDir/gitignore ~/.gitignore

git config --global user.name "Maxim Kulkin"
git config --global user.email "maxim.kulkin@gmail.com"
git config --global push.default simple
git config --global rerere.enabled true
git config --global rebase.autosquash true
git config --global core.excludesFile ~/.gitignore

# Configure kitty
mkdir -p ~/.config/kitty
ln -s $relativeDir/kitty.conf ~/.config/kitty/kitty.conf

